// Do not edit this file. It was auto-generated by saveApiMocks.ts
import { bpt_25USDC_50FLY_25stSMock } from './bpt_25USDC_50FLY_25stSMock'
import { bpt_scUSD_stSMock } from './bpt_scUSD_stSMock'
import { bpt_anS_SiloWSMock } from './bpt_anS_SiloWSMock'
import { Pool } from '../../pool.types'

export const allApiMocks: Pool[] = [
  bpt_25USDC_50FLY_25stSMock,
  bpt_scUSD_stSMock,
  bpt_anS_SiloWSMock,
]
 