import type { GqlPoolAprItem } from '../services/api/graphql-derived-types'
import type { GqlChain, GqlHookType, GqlPoolAprItemType } from '../services/api/generated/graphql'
import { GqlHookTypeValues, GqlPoolAprItemTypeValues } from '../services/api/graphql-enums'
import { bn } from '../utils/numbers'
import type BigNumber from 'bignumber.js'

export const swapFeesTooltipText = `LPs earn fees when swaps are routed through this pool. The displayed APR is net earnings for LPs (with all protocol fees already deducted). Fees automatically compound into positions—no claiming needed.`

export const inherentTokenYieldTooltipText = `LPs earn the inherent yield from yield bearing tokens. The displayed APR is net earnings for LPs, accounting for the token’s share of the pool (with all protocol fees already deducted). Fees automatically compound into positions—no claiming needed.`

export const merklIncentivesTooltipText = `Merkl is a platform that allows 3rd party Incentive Providers
 to offer campaigns with additional yield for Liquidity Providers.`

const maBeetsVotingRewardsTooltipText =
  'To receive Voting APR you must vote for incentivized pools in the bi-weekly gauge vote. APR is dependent on your vote distribution.'

const maBeetsRewardTooltipText = 'This APR is determined by the maturity of the Relic.'

const quantAMMTooltipText =
  "The annualized monthly uplift per LP token. The uplift is generated by the BTF strategy's dynamic rebalancing of the pool weights compared to a fixed weight pool. This uplift is shared with LPs proportionately."

// Only include the hook types we currently support irt dynamic swap fees
export type SupportedHookType = Extract<
  GqlHookType,
  typeof GqlHookTypeValues.MevTax | typeof GqlHookTypeValues.StableSurge
>

export const dynamicSwapFeesTooltipText: Record<SupportedHookType, string> = {
  [GqlHookTypeValues.MevTax]:
    'The MEV captured and shared to all LPs proportionately by the ‘MEV Capture’ hook used in this pool.',
  [GqlHookTypeValues.StableSurge]:
    'Additional swap fees from the directional fee StableSurge hook that dynamically adjusts to protect stable-asset pegs during volatility. These fees auto-compound and are shared with LPs proportionately.',
}

// Types that must be added to the total base
const TOTAL_BASE_APR_TYPES: GqlPoolAprItemType[] = [
  GqlPoolAprItemTypeValues.SwapFee24h,
  GqlPoolAprItemTypeValues.IbYield,
  GqlPoolAprItemTypeValues.Staking,
  GqlPoolAprItemTypeValues.Merkl,
  GqlPoolAprItemTypeValues.MaBeetsEmissions,
  GqlPoolAprItemTypeValues.QuantAmmUplift,
]

// Types that must be added to the total APR
export const TOTAL_APR_TYPES: GqlPoolAprItemType[] = [
  ...TOTAL_BASE_APR_TYPES,
  GqlPoolAprItemTypeValues.Voting,
  GqlPoolAprItemTypeValues.StakingBoost,
]

export function useAprTooltip({
  aprItems,
  numberFormatter,
}: {
  aprItems: GqlPoolAprItem[]
  numberFormatter: (value: string) => BigNumber
  chain: GqlChain
}) {
  // Swap fees
  const swapFee = aprItems.find(item => item.type === GqlPoolAprItemTypeValues.SwapFee24h)
  const swapFeesDisplayed = numberFormatter(swapFee ? swapFee.apr.toString() : '0')

  // Dynamic swap fees (MEV Capture, StableSurge)
  const dynamicSwapFee = aprItems.find(
    item => item.type === GqlPoolAprItemTypeValues.DynamicSwapFee24h
  )

  const dynamicSwapFeesDisplayed = numberFormatter(
    dynamicSwapFee ? dynamicSwapFee.apr.toString() : '0'
  )

  // QuantAMM fees
  const quantAMMFee = aprItems.find(item => item.type === GqlPoolAprItemTypeValues.QuantAmmUplift)
  const quantAMMFeesDisplayed = numberFormatter(quantAMMFee ? quantAMMFee.apr.toString() : '0')

  // Yield bearing tokens
  const yieldBearingTokens = aprItems.filter(item => {
    return item.type === GqlPoolAprItemTypeValues.IbYield
  })

  const yieldBearingTokensDisplayed = yieldBearingTokens.map(item => ({
    title: item.rewardTokenSymbol || '',
    apr: numberFormatter(item.apr.toString()),
  }))

  const yieldBearingTokensAprDisplayed = yieldBearingTokensDisplayed.reduce(
    (acc, item) => acc.plus(item.apr),
    bn(0)
  )

  // Staking incentives
  const stakingIncentives = aprItems.filter(item => {
    return item.type === GqlPoolAprItemTypeValues.Staking
  })

  const stakingIncentivesDisplayed = stakingIncentives.map(item => ({
    title: item.rewardTokenSymbol || '',
    apr: numberFormatter(item.apr.toString()),
    tooltipText: `3rd party incentives for LPs who stake. These token incentives are outside the gauge bounty system.`,
  }))

  const votingApr = aprItems.find(item => item.type === GqlPoolAprItemTypeValues.Voting)
  const votingAprDisplayed = numberFormatter(votingApr ? votingApr.apr.toString() : '0')

  // Merkl incentives
  const merklIncentives = filterByType(aprItems, GqlPoolAprItemTypeValues.Merkl)
  const hasMerklIncentives = merklIncentives.length > 0
  const merklIncentivesAprDisplayed = calculateSingleIncentivesAprDisplayed(merklIncentives)

  const merklTokens = aprItems.filter(item => {
    return item.type === GqlPoolAprItemTypeValues.Merkl
  })

  const merklTokensDisplayed = merklTokens.map(item => ({
    title: item.rewardTokenSymbol || '',
    apr: numberFormatter(item.apr.toString()),
  }))

  // maBEETS Rewards (Beets)
  const maBeetsReward = aprItems.find(
    item => item.type === GqlPoolAprItemTypeValues.MaBeetsEmissions
  )

  const maBeetsRewardsDisplayed = numberFormatter(
    maBeetsReward ? maBeetsReward.apr.toString() : '0'
  )

  const maxMaBeetsReward = aprItems.find(
    item => item.type === GqlPoolAprItemTypeValues.StakingBoost && item.id.match(/beets-apr-boost/) // TODO: or add prop in api to distinguish?
  )

  const maxMaBeetsRewardDisplayed = numberFormatter(
    maxMaBeetsReward ? maxMaBeetsReward.apr.toString() : '0'
  )

  const maxMaBeetsVotingReward = aprItems.find(
    item => item.type === GqlPoolAprItemTypeValues.StakingBoost && item.id.match(/voting-apr-boost/) // TODO: or add prop in api to distinguish?
  )

  const maxMaBeetsVotingRewardDisplayed = numberFormatter(
    maxMaBeetsVotingReward ? maxMaBeetsVotingReward.apr.toString() : '0'
  )

  const maBeetsTotalAprDisplayed = bn(swapFeesDisplayed)
    .plus(yieldBearingTokensAprDisplayed)
    .plus(maBeetsRewardsDisplayed)
    .plus(maxMaBeetsRewardDisplayed)
    .plus(maxMaBeetsVotingRewardDisplayed)

  const isMaBeetsPresent = !maxMaBeetsVotingRewardDisplayed.isZero()

  const totalBase = aprItems
    .filter(item => TOTAL_BASE_APR_TYPES.includes(item.type))
    .reduce((acc, item) => acc.plus(item.apr), bn(0))

  const totalBaseDisplayed = numberFormatter(totalBase.toString())

  const totalCombined = aprItems
    .filter(item => TOTAL_APR_TYPES.includes(item.type))
    .reduce((acc, item) => acc.plus(item.apr), bn(0))

  const totalCombinedDisplayed = numberFormatter(totalCombined.toString())

  const stakingIncentivesAprDisplayed = stakingIncentivesDisplayed.reduce(
    (acc, item) => acc.plus(item.apr),
    bn(0)
  )

  const isSwapFeePresent = !swapFeesDisplayed.isZero()
  const isYieldPresent = !yieldBearingTokensAprDisplayed.isZero()
  const isStakingPresent = !stakingIncentivesAprDisplayed.isZero()

  const isVotingPresent = !votingAprDisplayed.isZero()

  const subitemPopoverAprItemProps = {
    pt: 2,
    pl: 'sm',
    backgroundColor: 'background.level1',
    fontWeight: 500,
    fontColor: 'gray.400',
  }

  return {
    totalBaseDisplayed,
    yieldBearingTokensAprDisplayed,
    stakingIncentivesAprDisplayed,
    swapFeesDisplayed,
    isSwapFeePresent,
    isYieldPresent,
    isStakingPresent,
    yieldBearingTokensDisplayed,
    stakingIncentivesDisplayed,
    merklIncentivesAprDisplayed,
    merklTokensDisplayed,
    hasMerklIncentives,
    votingAprDisplayed,
    isVotingPresent,
    subitemPopoverAprItemProps,
    totalBase,
    totalCombined,
    totalCombinedDisplayed,
    isMaBeetsPresent,
    maBeetsRewardsDisplayed,
    maxMaBeetsRewardDisplayed,
    maBeetsRewardTooltipText,
    maxMaBeetsVotingRewardDisplayed,
    maBeetsVotingRewardsTooltipText,
    maBeetsTotalAprDisplayed,
    dynamicSwapFeesDisplayed,
    dynamicSwapFeesTooltipText,
    quantAMMTooltipText,
    quantAMMFeesDisplayed,
  }
}

function filterByType(aprItems: GqlPoolAprItem[], type: GqlPoolAprItemType) {
  return aprItems.filter(item => {
    return item.type === type
  })
}

function calculateSingleIncentivesAprDisplayed(aprItems: GqlPoolAprItem[]) {
  return aprItems.reduce((acc, item) => acc.plus(item.apr), bn(0))
}
